### ISSUE TITLE
Upstreaming the win_pendingreboot module ?

### ISSUE THREAD

**Issue by dagwieers** [trondhindenes/ansibleroles-winreboot#3]
Are you planning to contribute the win_pendingreboot module to the Ansible project ?

**Comment by trondhindenes** [comment]
Hi, I guess I could. Let me clean up the code and submit a PR.

**Comment by dagwieers** [comment]
Great ! We are planning to use it.

I also have a small wishlist for additional WIndows modules, but as a die-hard Linux user Powershell does not feel very natural. Is there a community of Windows-Ansible users, or a backlog of things to come for Windows users ?

**Comment by trondhindenes** [comment]
There's definetely a community, but not an official backlog. If you are using a newer version of PowerShell (5.0+) there's a ton of extra modules autogenerated from the PowerShell community's DSC resources (you can find these ready to use in Ansible here: https://github.com/trondhindenes/Ansible-Auto-Generated-Modules )

I'd get on the Ansible's google group, or maybe submit a pr to the "roadmap" repo (under ansible) for anything you'd like to see.

**Comment by dagwieers** [comment]
Thanks, that was very helpful !

As a long-time Linux developer, Powershell does look very awkward though.

**Comment by trondhindenes** [comment]
Ha, I can understand that. It's object-oriented so instead of comparing it
to bash, think of it as a weird relative of python. Much more similar :-)

**Comment by dagwieers** [comment]
Well, to be honest. It reminds me more of Jinja2 (which I would not choose
as a programming language of my choice).
But I am sure once I throw myself in Microsoft's arms I will get the hang
of it ;-)

It does require a lot of Windows design information, especially if you
require registry editing.
(e.g. I'd like to modify the Windows mouse cursor/theme to extra large, but
that's a hell of a job to do apparently)

**Comment by trondhindenes** [comment]
@dagwieers just a fyi: a reboot check is now merged upstream. You'll be getting "ansible_reboot_pending" true/false from your windows nodes (as long as you haven't disabled fact checking) from this commit:
https://github.com/ansible/ansible-modules-core/pull/3879#event-683503927

**Comment by dagwieers** [comment]
@trondhindenes Perfect, thanks !

**Comment by nitzmahone** [comment]
@dagwieers as the keeper of the Windows Ansible core stuff these days, I'd love to hear any ideas/wishlist kinds of things you have around Windows. The 2.2 roadmap isn't set in stone yet, so there's still potentially things we can move around if you have needs that might be compelling to a lot of our Windows userbase.

**Comment by dagwieers** [comment]
@nitzmahone I have a few suggestions to make it easier for Windows users:
- Add the generic action plugins (`raw`, `script`, ...) to the Windows modules category
  - Linking the .py files will probably do the trick -> ansible/ansible-modules-core#3896
  - Also see ansible/ansible#16255
- Get rid of the useless .py files for documentation
  - Powershell .ps1 files could have the docs included, just like Python modules
- Implement `win_command` or `win_shell`, instead of using the `raw` action plugin
  - Or make the generic `command` and `shell` modules work for Windows/Powershell too
- Make `win_copy` and `win_template` work as resp. `copy` and `template` from within Ansible
  - In effect, if connection method is `winrm`, we should be looking for .ps1 files, not .py
- The `raw` action plugin always returns ok, while it should return a change by default
- Implement check-mode (and diff-mode) in as many Windows modules as possible
- When using connection `winrm` using a password prompt, the prompt still states `SSH password:`
- Implement `become_method: runas` -> ansible/ansible#16202
  - If the connection method is `winrm` the `become_method` could be `runas` by default
- Document Client Certificate Authentication using winrm -> ansible/ansible#16243
- Pipelining for WinRM connection method
- Implement a squash_action for win_chocolatey
- Implement a config section `[winrm_connection]` cfr. ssh and paramiko, for configuring
  - `cert_key_pem`
  - `cert_pem`
  - `pipelining`
  - `server_cert_validation`
  - `transport`
  - `verify`

Maybe we ought to make issues out of each of these ?
